name: 'GitHub Action to build a static notes site'
inputs:
  source_directory:
    description: 'Path to notes directory'
    required: true
    default: "./"
  build_directory:
    description: 'Destination path for static site'
    required: true
    default: "site/"

runs:
  using: "composite"
  steps:
    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.10'

    - name: Run build script
      shell: bash
      run: |
        julia "$GITHUB_ACTION_PATH/build.jl" "${{ inputs.source_directory }}" "${{ inputs.build_directory }}"
